version: '3'
services:
  redis:
    container_name: redis
    image: redis:alpine

  worker:
    container_name: worker
    build:
      context: .
      target: worker
    entrypoint: celery
    command: -A tasks worker -l info -E
    user: nobody
    volumes:
      - ./src:/data
    working_dir: /data
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      PYTHONPATH: /data
    depends_on:
      - redis
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:5140
        tag: "worker.{{.Name}}"
        fluentd-async-connect: "true"

  flower:
    container_name: flower
    build:
      context: .
      target: worker
    command: celery -A tasks flower --loglevel=info
    volumes:
      - ./src:/data
    working_dir: /data
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      FLOWER_UNAUTHENTICATED_API: "true" # 認証しなくてもterminateできるようになる
    depends_on:
      - worker
      - redis

  fluentd:
    container_name: fluentd
    build:
      context: .
      target: fluentd
    # image: fluent/fluentd:v1.16.2-debian-1.0
    volumes:
      - ./fluentd:/fluentd/etc
    ports:
      - "5140:5140"
      - "5140:5140/udp"
